### ISSUE TITLE
Value for "admin" field in Users table incorrectly set to false.

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry/cloud_controller_ng#104]
In a cf deployment with a deployment manifest that includes the following properties:

```
  uaa:
...
    scim:
      users:
      - admin|c1oudc0w|scim.write,scim.read,openid,cloud_controller.admin
      - services|c1oudc0w|scim.write,scim.read,openid,cloud_controller.admin
```

results in a ccdb "Users" table with the following values:

```
ccdb=> select * from users;
 id |                 guid                 |         created_at         | updated_at | default_space_id | admin | active
----+--------------------------------------+----------------------------+------------+------------------+-------+--------
  1 | d1bcb0ba-5553-4310-a725-f5a8236893b6 | 2013-08-26 18:47:32.020244 |            |                  | f     | t
  2 | 0a913c96-1641-42fb-bea6-c02fb3cf1db3 | 2013-10-14 14:36:48.096586 |            |                  | t     | t
```

and is then reflected in the cf users command as follows:

```
→ cf users
Getting users... OK
admin:
  admin?: false

services:
  admin?: true
```
