### ISSUE TITLE
Provide better error message for case where custom command in app manifest is too long

### ISSUE THREAD

**Issue by cdavisafc** [cloudfoundry/cloud_controller_ng#108]
Currently when you try to push an app with a manifest that contains a long custom command, say a manifest such as 

```

---
applications:
- name: helloplay2
  memory: 256M
  instances: 1
  host: helloplay2
  domain: cdavisafc.cf-app.com
  command: JAVA_HOME=/app/.java PATH=$JAVA_HOME/bin:$PATH echo "DB_URL=jdbc:h2:tcp://11.111.111.111:9092//home/ubuntu/abcd.db&" | python helloworld-1.0/pre-install/preinstall.py && JAVA_HOME=/app/.java PATH=$JAVA_HOME/bin:$PATH python helloworld-1.0/install/install.py -Dhttp.port=$PORT
```

results in an output such as:

```
○ → cf push
Using manifest file manifest.yml

Creating helloplay2... FAILED
CFoundry::InvalidRequest: 10004: The request is invalid
```

Digging into the cc logs shows that this is a length problem:

```
{"timestamp":1381891009.0965514,"message":"Mysql2::Error: Data too long for column 'metadata' at row 1: INSERT INTO `apps` (`name`, `production`, `space_id`, `salt`, `encrypted_environment_json`, `environment_json`, `memory`, `instances`, `disk_quota`, `state`, `metadata`, `stack_id`, `guid`, `created_at`, `version`) VALUES ('helloplay2', 0, 1, '30a1542f', 'Xd+yf84SUNmZ6z8hlpTfaA==\\n', '{}', 256, 1, 1024, 'STOPPED', '{\\\"command\\\":\\\"JAVA_HOME=/app/.java echo \\\\\\\"DB_URL=jdbc:h2:tcp://54.227.240.121:9092//home/ubuntu/abcd.db&\\\\\\\" | python helloworld-1.0/pre-install/preinstall.py && JAVA_HOME=/app/.java PATH=$JAVA_HOME/bin:$PATH python helloworld-1.0/install/install.py -Dhttp.port=$PORT\\\",\\\"console\\\":false}', 1, 'bbacb7cf-1f30-4aa1-86c8-84dbab01602e', '2013-10-16 02:36:49', 'ba445285-0da9-4df0-8ea8-e0223943d40a')","log_level":"error","source":"cc.db","data":{"request_guid":"77516eab-8d9c-487a-a108-fb940f884224"},"thread_id":42889940,"fiber_id":44741460,"process_id":11198,"file":"/var/vcap/packages/cloud_controller_ng/cloud_controller_ng/vendor/bundle/ruby/1.9.1/gems/sequel-3.48.0/lib/sequel/database/logging.rb","lineno":70,"method":"block in log_each"}
```

This is happening on AWS deployments of CF but not on some other, non-AWS deployments.

At a minimum the error message to should let the developer pushing the app (who generally won't have access to the cc logs) what the real issue is.
