### ISSUE TITLE
Add support for arbitrary parameters when binding services via manifest.yml

### ISSUE THREAD

**Issue by geoffwa** [cloudfoundry/cloud_controller_ng#1332]
The CLI doesn't currently support arbitrary parameters for binding services via a manifest.yml file: https://docs.cloudfoundry.org/devguide/services/application-binding.html#-binding-with-application-manifest

For NFS volume mounts: https://docs.cloudfoundry.org/devguide/services/using-vol-services.html#create it's quite useful to specify the mount path and uid/gids when binding an NFS service to one or more apps.

Are there any blockers to adding this support?

**Comment by tcdowney** [comment]
We shipped this functionality in [capi-release 1.80.0](https://github.com/cloudfoundry/capi-release/releases/tag/1.80.0). Closing this issue.

**Comment by KrisPetkov** [comment]
Hello guys, I have a question related to this functionality: at our team we have a broker application which is being bound with other application through the `-c '{"some_key":"some_value"}'` option of the `cf bs` command. We are trying to migrate to this new functionality, so we can bind application which are passing arbitrary parameters from the manifest. But when there is an application which is trying to pass the parameters from its manifest nothing happens i.e.

```yaml
---
applications:
- name: test-app
  memory: 256M
  instances: 1
  random-route: true
  services:
  - name: test-private-service
    binding_name: some-binding
    parameters:
      readonly: true
      mount: "/usr/some_test_dir"
      meter: true

```

Our broker application does not receive any parameters specified in the manifest when the user executes the `cf push` command. In our broker app the RawParameters of the domain.BindDetails are empty. If the user tries to use the `-c '{"some_key":"some_value"}'` instead of the manifest approach everything works fine. We are using **CF CLI v7** and the **capi version is 1.106.0**. 

Is there anyone facing the same problem or knows what should be done?

Thanks!
