### ISSUE TITLE
Question: why container metrics does not tell us the real memory consumption

### ISSUE THREAD

**Issue by amber-yan** [cloudfoundry/cloud_controller_ng#2144]
I have a NodeJs application and I create a docker image for it. I push this docker image to cf. 
The manifest file like the following: 
```
Version: 1
applications:
- docker:
    image: deploy-releases.docker.repositories.com/myapp-201112-1606852710-fd13409:latest
    username: hana-tooling-build
    env:
      HEALTH_ERROR: ''
      HEALTH_PRODUCT: ''
      SAP_JWT_TRUST_ACL: '[ { "clientid" : "*","identityzone" : "*" } ]'
    name: myapp-201112-1606852710-fd13409
    processes:
    - disk_quota: 2GB
      health-check-http-endpoint: /health
      health-check-invocation-timeout: 10
      health-check-type: http
      instances: 2
      memory: 512MB
      timeout: 120
      type: web
```

And myapp often crashes with status 2. I checked the logs and found it is indeed a memory issue. The application hit the memory issue on start-up. My system collects the app container metrics and the max memory usage is low. So, I am confused why the app crash with the memory limit but the memory usage is low.  The container metrics are described on the doc https://docs.cloudfoundry.org/loggregator/container-metrics.html. 
![image](https://user-images.githubusercontent.com/77049779/110437322-36831a00-80f0-11eb-8276-110ca99c0b22.png)

I'd like to confirm : 
1.  Does the memory of container metrics include the application memory consumption on start-up?
2. If container metrics does not contain the memory consumption of the application startup, how can I get the maximum memory required in app startup stage?
3. Will the memory I set in manifest be applied to my NodeJs app or the entire container?
4. If the memory in manifest is applied to the entire container, how much memory will my NodeJs application be allocated？

I am not sure if this repo is the right place to open this issue, if it is not, can you tell me the right place? 
Thanks 

Yan
