### ISSUE TITLE
cf cli always shows the default_route as being set to true when not specified in the manifest

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2198]
To reproduce:

manifest.yaml:
```
applications:
- name: morc2
  buildpacks:
  - go_buildpack
  env:
    GOPACKAGENAME: cora
    VAR: foobar
  processes:
  - type: web
    instances: 2
```
note: default_route is not specified.

Using the cf v8 cli note the `default-route: true` is being being added to the manifest, and set when it was not included in the manifest.
```
±  |develop U:2 ✗| → cf push
Pushing app morc2 to org org / space space as admin...
Applying manifest file /home/pivotal/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/pora/manifest.yml...

Updating with these attributes...
  ---
  applications:
+ - name: morc2
+   processes:
+   - instances: 2
+     type: web
    default-route: true
+   buildpacks:
+   - go_buildpack
+   env:
+     GOPACKAGENAME: cora
+     VAR: foobar
Manifest applied
```
