### ISSUE TITLE
**CLI** user should NOT see a **diff** when **removing routes**

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2200]
**Context**

Removing routes from a manifest does not unmap them from the app or delete the route. Showing routes removed from the manifest in the diff can confuse people into thinking the routes will be unmapped and/or deleted.

---

**Acceptance Criteria**

### Omit Route Removals

**Given** an app named `my-app` 
**And** it is mapped to two routes `one.example.com` and `two.example.com`
**When** I apply the following manifest
```yaml
---
applications:
  - name: my-app
    routes:
      - route: two.example.com
```
**Then** the route `one.example.com` should not show up as being removed in the diff

---

Notes:
- The manifest diff endpoint should not return route deletions, so this logic can be shared across all clients
