### ISSUE TITLE
API endpoint `manifest_diff` is incorrectly marking sidecar values as being removed when they are not provided in the manifest

### ISSUE THREAD

**Issue by tstannard** [cloudfoundry/cloud_controller_ng#2259]
## Issue
The api endpoint `manifest_diff` is returning a remove in the sidecar array when a default value is not included in the provided manifest but was there previously. 

## Context

When a value is removed from a manifest we do not want to see it as removed in the manifest since the provided manifest is idempotent. 

## Steps to Reproduce

1. 
Push app with sidecar specified in the manifest

```
- name: app_name
- sidecars:
   - name: sleep_agent
     process_types: [ 'web', 'worker' ]
     command: sleep 1000
     memory: 1M
```

2. 
Remove memory field from the sidecar in the manifest
```
- name: app_name
- sidecars:
   - name: sleep_agent
     process_types: [ 'web', 'worker' ]
     command: sleep 1000
```
3.
Curl the manifest diff endpoint
```
cf curl /v3/spaces/<space guid>/manifest_diff -d @./manifest.yml -H "Content-Type: application/x-yaml"
```

## Expected result

The diff should be empty. 
```
{
  "diff": []
}
```

## Current result

The diff marks the memory as removed every time. 

```
{
  "diff": [
    {
      "op": "remove",
      "path": "/applications/1/sidecars/0/memory",
      "was": "1M"
    }
  ]
}
```

## Possible Fix

Only include the keys in the provided manifest in the diff. Look at [process logic](https://github.com/cloudfoundry/cloud_controller_ng/commit/9c796d83da5723d576e8430fa30186c063e6fdcb) for a prior art
