### ISSUE TITLE
Manifest generation should show full service configuration information

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/cloud_controller_ng#2723]
## Issue

Currently, if a service for an app was configured with parameters other than name (e.g. the `parameters` or `binding_name` field), they will not be shown when generating a manifest.

## Context
Let's say we push an app with a manifest like so:

```
---                                                                                                                                                                                                              
applications:
- name: dora
  services:
  - name: my-service
    binding_name: my-binding
    parameters:
      foo: bar    
```

When we curl /v3/apps/:guid/manifest, this is what we receive:

```
---                                                                                                                                                                                                              
applications:
- name: dora
  services:
  - my-service

```


This could be an issue if one were to try applying a manifest to a different space or org to duplicate an app.  It also causes or exacerbates issues with manifest diffs, such as https://github.com/cloudfoundry/cloud_controller_ng/issues/2201, where we cannot generate a proper diff because the logic between that endpoint and the manifest diff generation are shared.


## Possible Fix

Always render services in their full configuration, instead of always rendering just their name.
