### ISSUE TITLE
New security_groups not apply  ?

### ISSUE THREAD

**Issue by shinji62** [cloudfoundry/cloud_controller_ng#310]
Hello,

I add a security_groups into my CF manifest and this networks is not available I could not list him with the cli and is not in ccdb  : 

```
 security_group_definitions:
    - name: company_networks
      rules:
      - destination: 100.67.0.0-100.69.255.255
        protocol: all
      - destination: 172.18.0.0-172.18.255.255
        protocol: all
    - name: public_networks
      rules:
      - destination: 0.0.0.0-9.255.255.255
        protocol: all
      - destination: 11.0.0.0-169.253.255.255
        protocol: all
      - destination: 169.255.0.0-172.15.255.255
        protocol: all
      - destination: 172.18.0.0-192.167.255.255
        protocol: all
      - destination: 192.169.0.0-255.255.255.255
        protocol: all
    - name: dns
      rules:
      - destination: 0.0.0.0/0
        ports: "53"
        protocol: tcp
      - destination: 0.0.0.0/0
        ports: "53"
        protocol: udp
    default_running_security_groups:
    - company_networks
    - dns
    default_staging_security_groups:
    - public_networks
    - dns

```

I am using the last cf-release v191.
Any idea?
