### ISSUE TITLE
[BUG] Generate manifest api schema inconsistency for services

### ISSUE THREAD

**Issue by Gourab1998** [cloudfoundry/cloud_controller_ng#3683]
## Issue

Generate manifest schema inconsistency for services

## Context

On call to  "/v3/apps/$GUID/manifest" api returns the services as array of strings when expected was array of objects.
This inconsistency creates problem for strongly typed clients.

## Steps to Reproduce

cf push 

```yaml
applications:
- name: http-bin
  docker:
    image: kennethreitz/httpbin
  services:
  - name: xsuaa-tf
  processes:
  - type: web
    disk_quota: 1024M
    health-check-type: http
    health-check-http-endpoint: /get
    instances: 1
    memory: 256M
    readiness-health-check-type: http
    readiness-health-check-http-endpoint: /get
```
export GUID=$(cf app http-bin --guid)
cf curl "/v3/apps/$GUID/manifest"

```yaml
---
applications:
- name: http-bin
  docker:
    image: kennethreitz/httpbin
  services:
  - xsuaa-tf
  processes:
  - type: web
    instances: 1
    memory: 256M
    disk_quota: 1024M
    log-rate-limit-per-second: -1
    health-check-type: http
    health-check-http-endpoint: "/get"
    readiness-health-check-type: http
    readiness-health-check-http-endpoint: "/get"
```

## Expected result

I would expect the returned schema to have services as
```yaml
  services:
  - name: xsuaa-tf
```

## Current result

Currently we are getting array of strings even when we are pushing it as an array of objects.
