### ISSUE TITLE
Add ability to customise root links

### ISSUE THREAD

**Issue by Samze** [cloudfoundry/cloud_controller_ng#4306]
Today the `/` endpoint returns a set of services for discover related to the CF foundation. E.g UAA / Credhub CC V3 etc.

Often there are additional services deployed to the platform ontop of OSS CF that it would also be useful to be discoverable through this endpoint. For example a custom UI for developers.

Therefore we'd look to add a new bosh property that allowed arbtirary new entries to `/` links. e.g.

```
cf curl / | jq .
{
  "links": {
    "self": {
      "href": "https://api.sys.example.com"
    },
    "cloud_controller_v3": {
      "href": "https://api.sys.example.com/v3",
      "meta": {
        "version": "3.191.0"
      }
    },
    "network_policy_v0": {
      "href": "https://api.sys.example.com/networking/v0/external"
    },
    "network_policy_v1": {
      "href": "https://api.sys.example.com/networking/v1/external"
    },
    "login": {
      "href": "https://login.sys.example.com"
    },
    "uaa": {
      "href": "https://uaa.sys.example.com"
    },
    "credhub": null,
    "routing": {
      "href": "https://api.sys.example.com/routing"
    },
    "logging": {
      "href": "wss://doppler.sys.example.com:443"
    },
    "log_cache": {
      "href": "https://log-cache.sys.example.com"
    },
    "log_stream": {
      "href": "https://log-stream.sys.example.com"
    },
    "app_ssh": {
      "href": "https://foo.example.com",
      "meta": {
        "host_key_fingerprint": "123",
        "oauth_client": "ssh-proxy"
      }
    },
    "my-service": { ### << custom service
       "href": "https://my-service.example.com"
     }
  }
}
```

This property would be something like:
```

  cc.custom_root_links:
    description: "Array of custom links to be added to the root '/' endpoint. These will override the default links if the same name is used."
    example: |
      - name: my-service
        href: https://my-service.example.com
```
