### ISSUE TITLE
Support the ability to run Processes with a user other than`vcap`

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/cloud_controller_ng#4372]
## Problem

Apps with the CNB or Buildpack lifecycle¹ always run as the `vcap` user. This effectively hardcodes assumptions about the [underlying stack](https://github.com/cloudfoundry/cflinuxfs4/blob/d10cd4a40f5b2add77807e1b5d9f532213a6b3c2/Dockerfile#L26) supporting a user named `vcap` in CAPI and is not flexible for other runtimes/stacks. Some stacks like Windows have permissions and behaviors for its built in users -- `ContainerUser` and `ContainerAdmin` -- that the `vcap` user cannot inherit (see: https://github.com/microsoft/Windows-Containers/issues/390).

¹ Docker apps have more flexibility here and can [run as the user declared in the image metadata](https://github.com/cloudfoundry/cloud_controller_ng/blob/main/lib/cloud_controller/diego/docker/desired_lrp_builder.rb#L71).

## Proposal

We make `user` a first-class property on the `Process` that when set will override `vcap`. To prevent misuse while maintaining flexibility we will introduce a new config property in capi-release to serve as an allow list of valid usernames.

Example BOSH spec:

```
cc.allowed_process_users:
    description: "Permitted users that processes may use"
    default: ['vcap']
```

We will modify the [Update a Process](https://v3-apidocs.cloudfoundry.org/version/3.195.0/index.html#update-a-process) API and app manifest to accept the `user` field.

Example manifest:

```
---
version: 1
applications:
- name: dot-net-app
  stack: windows
  processes:
  - type: web
    user: 'containeruser'
```

Any Process that has a `user` set will then use this value in place of any defaults.

### What if the app does not support the specified user?

If the app does not actually support running as this user then it will fail to start. Attempting to create and set up permissions for arbitrary users is out of scope of this proposal.

## Alternatives Considered

We considered making a new app feature for Windows apps called `windows-run-as-containeruser`. However this felt too inflexible and specific to a particular use case to be a general app feature. Rather than do that, we feel that making a proper developer-settable `user` field will account for unforeseen use cases in the future and open up the ability to support stacks/buildpacks that don't use `vcap`.

**Comment by tcdowney** [comment]
Another thing to think about is how the proposed allow list applies to Docker apps which already have more complicated logic here:

```
        def action_user
          execution_metadata = Oj.load(@execution_metadata)
          user = execution_metadata['user']
          if user.nil? || user.empty?
            'root'
          else
            user
          end
        end
```

On one hand I don't think defaulting to running as `root` is necessarily the most secure thing to do. But I realize we don't want to break existing apps that have that set. The allow list is also inflexible for users who want the image to run as the user it declares. I'm just spitballing here, but we might need multiple options for Docker to remain compatible.

```
cc.allowed_process_users:
    description: "Permitted users that app containers may use"
    default: ['vcap']

cc.docker.permit_root_user:
    description: "Docker containers may run using the root user. This option takes precedence over cc.allowed_process_users."
    default: true

cc.docker.permit_user_from_image_metadata:
    description: "Docker containers may run using user specified in image metadata. This option takes precedence over cc.allowed_process_users."
    default: true
```
