### ISSUE TITLE
"actor_name": null  when querying app events if the actor is granted using client_credentials

### ISSUE THREAD

**Issue by boyang9527** [cloudfoundry/cloud_controller_ng#577]
## Issue

when I am granted using client-credential and use CC API to update an application, the events shows the actor_name is null, while the name of the client ID is not null.

## Context

Here is part of the response I got
```
         "entity": {
            "type": "audit.app.update",
            "actor": "cf-autoscaler-client",
            "actor_type": "user",
            "actor_name": null,
            "actee": "9fd12ebf-efaf-4a12-b97c-3e9f8715a651",
            "actee_type": "app",
            "actee_name": "ScalingTestApp",
            "timestamp": "2016-04-15T22:27:12Z",
            "metadata": {
               "request": {
                  "instances": 1
               }
            },
            "space_guid": "f5915cd0-adc8-4644-9edc-d878d321c77b",
            "organization_guid": "93bc82dd-a981-4058-867b-721573e37f6a"
         }
```

Here is client ID information: 

```
$uaac client get cf-autoscaler-client
  scope: uaa.none
  client_id: cf-autoscaler-client
  resource_ids: none
  authorized_grant_types: client_credentials
  autoapprove: 
  action: none
  authorities: cloud_controller.read cloud_controller.admin
  name: cf-autoscaler
  lastmodified: 1460755954283

```
