### ISSUE TITLE
Expose admin username/password via links

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/cloud_controller_ng#798]
As a service broker BOSH release author, I'd like to consume a link from a `cf` deployment on the same BOSH that contains the `system_domain` as well as other properties to allow consumers of the link to login + interact with the CF as an admin.

Perhaps:

```yaml
provides:
- name: cf_admin_user
  type: cf_user
  properties:
  - system_domain
  - admin_username
  - admin_password
  - skip_ssl_validation
```
